// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Estado de juego y jugador
type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Angle         float32                `protobuf:"fixed32,4,opt,name=angle,proto3" json:"angle,omitempty"`
	Health        float32                `protobuf:"fixed32,5,opt,name=health,proto3" json:"health,omitempty"` // Vida del jugador
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerState) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *PlayerState) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

// Estado de una bala
type BulletState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BulletId      string                 `protobuf:"bytes,1,opt,name=bullet_id,json=bulletId,proto3" json:"bullet_id,omitempty"` // Identificador único de la bala
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`                             // Posición X de la bala
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`                             // Posición Y de la bala
	Dx            float32                `protobuf:"fixed32,4,opt,name=dx,proto3" json:"dx,omitempty"`                           // Dirección X de la bala
	Dy            float32                `protobuf:"fixed32,5,opt,name=dy,proto3" json:"dy,omitempty"`                           // Dirección Y de la bala
	OwnerId       string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`    // ID del jugador que disparó la bala
	Damage        float32                `protobuf:"fixed32,7,opt,name=damage,proto3" json:"damage,omitempty"`                   // Daño que causa la bala
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletState) Reset() {
	*x = BulletState{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletState) ProtoMessage() {}

func (x *BulletState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletState.ProtoReflect.Descriptor instead.
func (*BulletState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *BulletState) GetBulletId() string {
	if x != nil {
		return x.BulletId
	}
	return ""
}

func (x *BulletState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BulletState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BulletState) GetDx() float32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *BulletState) GetDy() float32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

func (x *BulletState) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *BulletState) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

// Mensaje para eliminar una bala
type BulletRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BulletId      string                 `protobuf:"bytes,1,opt,name=bullet_id,json=bulletId,proto3" json:"bullet_id,omitempty"` // ID de la bala a eliminar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletRemoveRequest) Reset() {
	*x = BulletRemoveRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletRemoveRequest) ProtoMessage() {}

func (x *BulletRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletRemoveRequest.ProtoReflect.Descriptor instead.
func (*BulletRemoveRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *BulletRemoveRequest) GetBulletId() string {
	if x != nil {
		return x.BulletId
	}
	return ""
}

// Estado del juego
type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerState         `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"` // Lista de jugadores
	Bullets       []*BulletState         `protobuf:"bytes,2,rep,name=bullets,proto3" json:"bullets,omitempty"` // Lista de balas activas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameState) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetBullets() []*BulletState {
	if x != nil {
		return x.Bullets
	}
	return nil
}

// Obtener estado
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

// Mensaje para establecer el mapa
type MapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapNumber     int32                  `protobuf:"varint,1,opt,name=map_number,json=mapNumber,proto3" json:"map_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapRequest) Reset() {
	*x = MapRequest{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRequest) ProtoMessage() {}

func (x *MapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRequest.ProtoReflect.Descriptor instead.
func (*MapRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *MapRequest) GetMapNumber() int32 {
	if x != nil {
		return x.MapNumber
	}
	return 0
}

// Mensaje para responder con el mapa actual
type MapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapNumber     int32                  `protobuf:"varint,1,opt,name=map_number,json=mapNumber,proto3" json:"map_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapResponse) Reset() {
	*x = MapResponse{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapResponse) ProtoMessage() {}

func (x *MapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapResponse.ProtoReflect.Descriptor instead.
func (*MapResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *MapResponse) GetMapNumber() int32 {
	if x != nil {
		return x.MapNumber
	}
	return 0
}

// Mensaje para solicitar la adición de un nuevo jugador
type PlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"` // Nombre del jugador
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRequest) Reset() {
	*x = PlayerRequest{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRequest) ProtoMessage() {}

func (x *PlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRequest.ProtoReflect.Descriptor instead.
func (*PlayerRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// Mensaje para responder con el ID asignado al jugador
type PlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // ID único asignado al jugador
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResponse) Reset() {
	*x = PlayerResponse{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResponse) ProtoMessage() {}

func (x *PlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResponse.ProtoReflect.Descriptor instead.
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerResponse) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"t\n" +
	"\vPlayerState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x14\n" +
	"\x05angle\x18\x04 \x01(\x02R\x05angle\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x02R\x06health\"\x99\x01\n" +
	"\vBulletState\x12\x1b\n" +
	"\tbullet_id\x18\x01 \x01(\tR\bbulletId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x0e\n" +
	"\x02dx\x18\x04 \x01(\x02R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x05 \x01(\x02R\x02dy\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12\x16\n" +
	"\x06damage\x18\a \x01(\x02R\x06damage\"2\n" +
	"\x13BulletRemoveRequest\x12\x1b\n" +
	"\tbullet_id\x18\x01 \x01(\tR\bbulletId\"e\n" +
	"\tGameState\x12+\n" +
	"\aplayers\x18\x01 \x03(\v2\x11.game.PlayerStateR\aplayers\x12+\n" +
	"\abullets\x18\x02 \x03(\v2\x11.game.BulletStateR\abullets\"\a\n" +
	"\x05Empty\"+\n" +
	"\n" +
	"MapRequest\x12\x1d\n" +
	"\n" +
	"map_number\x18\x01 \x01(\x05R\tmapNumber\",\n" +
	"\vMapResponse\x12\x1d\n" +
	"\n" +
	"map_number\x18\x01 \x01(\x05R\tmapNumber\"0\n" +
	"\rPlayerRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\"-\n" +
	"\x0ePlayerResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId2\xc1\x03\n" +
	"\vGameService\x121\n" +
	"\vUpdateState\x12\x11.game.PlayerState\x1a\x0f.game.GameState\x12,\n" +
	"\fGetGameState\x12\v.game.Empty\x1a\x0f.game.GameState\x121\n" +
	"\x0fStreamGameState\x12\v.game.Empty\x1a\x0f.game.GameState0\x01\x12+\n" +
	"\tAddBullet\x12\x11.game.BulletState\x1a\v.game.Empty\x126\n" +
	"\fRemoveBullet\x12\x19.game.BulletRemoveRequest\x1a\v.game.Empty\x12'\n" +
	"\x06SetMap\x12\x10.game.MapRequest\x1a\v.game.Empty\x12(\n" +
	"\x06GetMap\x12\v.game.Empty\x1a\x11.game.MapResponse\x126\n" +
	"\tAddPlayer\x12\x13.game.PlayerRequest\x1a\x14.game.PlayerResponse\x12.\n" +
	"\rGetPlayerList\x12\v.game.Empty\x1a\x10.game.PlayerListB\aZ\x05/gameb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_game_proto_goTypes = []any{
	(*PlayerState)(nil),         // 0: game.PlayerState
	(*BulletState)(nil),         // 1: game.BulletState
	(*PlayerListItem)(nil),      // 2: game.PlayerListItem
	(*PlayerList)(nil),          // 3: game.PlayerList
	(*BulletRemoveRequest)(nil), // 4: game.BulletRemoveRequest
	(*GameState)(nil),           // 5: game.GameState
	(*Empty)(nil),               // 6: game.Empty
	(*MapRequest)(nil),          // 7: game.MapRequest
	(*MapResponse)(nil),         // 8: game.MapResponse
	(*PlayerRequest)(nil),       // 9: game.PlayerRequest
	(*PlayerResponse)(nil),      // 10: game.PlayerResponse
}
var file_game_proto_depIdxs = []int32{
	2,  // 0: game.PlayerList.players:type_name -> game.PlayerListItem
	0,  // 1: game.GameState.players:type_name -> game.PlayerState
	1,  // 2: game.GameState.bullets:type_name -> game.BulletState
	0,  // 3: game.GameService.UpdateState:input_type -> game.PlayerState
	6,  // 4: game.GameService.GetGameState:input_type -> game.Empty
	6,  // 5: game.GameService.StreamGameState:input_type -> game.Empty
	1,  // 6: game.GameService.AddBullet:input_type -> game.BulletState
	4,  // 7: game.GameService.RemoveBullet:input_type -> game.BulletRemoveRequest
	7,  // 8: game.GameService.SetMap:input_type -> game.MapRequest
	6,  // 9: game.GameService.GetMap:input_type -> game.Empty
	9,  // 10: game.GameService.AddPlayer:input_type -> game.PlayerRequest
	6,  // 11: game.GameService.GetPlayerList:input_type -> game.Empty
	5,  // 12: game.GameService.UpdateState:output_type -> game.GameState
	5,  // 13: game.GameService.GetGameState:output_type -> game.GameState
	5,  // 14: game.GameService.StreamGameState:output_type -> game.GameState
	6,  // 15: game.GameService.AddBullet:output_type -> game.Empty
	6,  // 16: game.GameService.RemoveBullet:output_type -> game.Empty
	6,  // 17: game.GameService.SetMap:output_type -> game.Empty
	8,  // 18: game.GameService.GetMap:output_type -> game.MapResponse
	10, // 19: game.GameService.AddPlayer:output_type -> game.PlayerResponse
	3,  // 20: game.GameService.GetPlayerList:output_type -> game.PlayerList
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
